### ISSUE TITLE
Service crashes

### ISSUE THREAD

**Issue by tebbbb** [artibex/piper-http#3]
I am running this Dockerfile and everything works when i generate a very short sentence. I can also generate it multiple times, but as soon as the text gets a bit longer (and i mean for example "Dies ist ein Test und so weiter bla bla bla", it will always fail when generating for a second time (even with different text). The error i get you can see below the code. A shorter text like "Dies ist ein Test und so" works every time. Also here is how i call the API:

` [2024-07-23 18:10:34] local.INFO: Executing command: curl --header "Content-Type: application/json" --request POST --data 'Dies ist ein Test und so weiter bla bla bla' --output '/var/www/html/public/audio/669ff21a45e5d6.99143831.wav' 'http://piper:5000/'`

```
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Get the latest version of the code
RUN apt update && apt install -y git && apt-get clean && apt-get autoremove -y

RUN git clone https://github.com/rhasspy/piper

# Update pip and install the required packages
RUN pip install --upgrade pip

# Set the working directory
WORKDIR /app/piper/src/python_run

# Install the package
RUN pip install -e .

# Install the requirements
RUN pip install -r requirements.txt

# Install http server
RUN pip install -r requirements_http.txt

RUN pip install wget

COPY run.py /app

COPY download /app/download

# Copy the folder of piper-voices/de into the container
WORKDIR /app/models

ENV MODEL_DOWNLOAD_LINK="https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/de/de_DE/thorsten/high/de_DE-thorsten-high.onnx?download=true"
ENV MODEL_TARGET_FOLDER="/app/models"
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENV SPEAKER="0"

# Run the webserver with python -m piper.http_server --model ...
CMD python /app/run.py "$MODEL_DOWNLOAD_LINK" "$MODEL_TARGET_FOLDER" "$SPEAKER"
```

  * Serving Flask app 'http_server' * Debug mode: onINFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead. * Running on all addresses (0.0.0.0) * Running on http://127.0.0.1:5000 * Running on http://172.26.0.2:5000INFO:werkzeug:Press CTRL+C to quitINFO:werkzeug: * Restarting with statWARNING:werkzeug: * Debugger is active!INFO:werkzeug: * Debugger PIN: 330-559-202INFO:werkzeug:172.26.0.3 - - [23/Jul/2024 16:50:20] "POST / HTTP/1.1" 200 -2024-07-23 16:50:28.118042925 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/Reshape_1' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:28 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) i < input_shape.NumDimensions() was false. The dimension with value zero exceeds the dimension size of the input tensor.INFO:werkzeug:172.26.0.3 - - [23/Jul/2024 16:50:28] "POST / HTTP/1.1" 500 -Traceback (most recent call last):  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__    return self.wsgi_app(environ, start_response)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app    response = self.handle_exception(e)               ^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app    response = self.full_dispatch_request()               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request    rv = self.handle_user_exception(e)         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request    rv = self.dispatch_request()         ^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/piper/src/python_run/piper/http_server.py", line 119, in app_synthesize    voice.synthesize(text, wav_file, **synthesize_args)  File "/app/piper/src/python_run/piper/voice.py", line 104, in synthesize    for audio_bytes in self.synthesize_stream_raw(  File "/app/piper/src/python_run/piper/voice.py", line 132, in synthesize_stream_raw    yield self.synthesize_ids_to_raw(          ^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/piper/src/python_run/piper/voice.py", line 183, in synthesize_ids_to_raw    audio = self.session.run(None, args, )[0].squeeze((0, 1))            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run    return self._sess.run(output_names, input_feed, run_options)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/Reshape_1' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:28 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) i < input_shape.NumDimensions() was false. The dimension with value zero exceeds the dimension size of the input tensor.

**Comment by artibex** [comment]
@tebbbb on what hardware are you running it? Perhaps it's a issue with the setup because it works once.

The piper project itself also points out that this is experimental. I created a image a long time ago that worked flawless for me and others at least. It could be that piper got a update that broke this setup sadly

**Comment by tebbbb** [comment]
@artibex 

 i fixed it by using this:

RUN pip install -U piper-phonemize
RUN pip install onnxruntime==1.17.1

instead of 

RUN pip install -r requirements.txt

Current version 1.18 doesnt seem to work. You can also see about it here: https://github.com/rhasspy/piper/issues/552 and in the onnxruntime repository were also issues reported if i remember correctly

I tried it on three different machines. One being my 2023 Lenovo L14 with a Ryzen 7 Pro, then a high performance Hetzner server and my shitty homeserver with an old Celeron. All the same results
